"""Generate frontend/tailwind.config.ts from the measured design system.

Never hand-edit the output. Change the captures or the normalisation policy and
re-run, so the config can never drift from what GHL actually renders.

Colour names come from GHL's own declared token names where the rendered value
matches one; otherwise a hex-derived name, which is a deliberate signal that GHL
renders a colour it never declared.
"""
import json
import pathlib
import re

RGB = re.compile(r"^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)$")


def to_css(v):
    m = RGB.match(v)
    if not m:
        return v
    r, g, b = (int(m.group(i)) for i in (1, 2, 3))
    a = m.group(4)
    if a is not None and float(a) < 1:
        return v
    return "#%02x%02x%02x" % (r, g, b)


def px_key(v):
    n = v.removesuffix("px")
    return n.replace(".", "_")


def main():
    system = json.loads(pathlib.Path("frontend/design-system.json").read_text(encoding="utf-8"))
    tokens = json.loads(pathlib.Path("frontend/tokens.json").read_text(encoding="utf-8"))
    declared = tokens["declared"]

    # value -> shortest declared token name
    by_val = {}
    for name, val in declared.items():
        v = val.strip().lower()
        n = name.lstrip("-")
        if v not in by_val or len(n) < len(by_val[v]):
            by_val[v] = n

    colours, unnamed = {}, 0
    for prop in ("color", "background-color", "border-top-color"):
        for v in system.get(prop, []):
            css = to_css(v)
            if css in colours.values():
                continue
            name = by_val.get(css.lower())
            if not name:
                name = "c" + css.lstrip("#")
                unnamed += 1
            colours[name] = css

    font_size = {px_key(v): v for v in system.get("font-size", [])}
    font_weight = {v: v for v in system.get("font-weight", [])}
    radius = {px_key(v): v for v in system.get("border-top-left-radius", [])}
    shadow = {"s%d" % i: v for i, v in enumerate(system.get("box-shadow", []))}

    spacing = {}
    for prop in ("padding-top", "padding-right", "padding-bottom", "padding-left",
                 "gap", "row-gap", "column-gap"):
        for v in system.get(prop, []):
            if v.endswith("px"):
                spacing[px_key(v)] = v

    def block(name, d, indent="   "):
        lines = ["  %s: {" % name]
        for k, v in sorted(d.items(), key=lambda kv: kv[0]):
            lines.append('%s"%s": "%s",' % (indent, k, v))
        lines.append("  },")
        return lines

    out = [
        "// GENERATED by capture/gen_tailwind.py from measured GHL values.",
        "// DO NOT EDIT. Re-run the generator instead.",
        "// Colour names are GHL's own token names where the rendered value matches a",
        "// declared token; 'c<hex>' names are colours GHL renders but never declared.",
        "import type { Config } from 'tailwindcss'",
        "",
        "export default {",
        "  content: ['./index.html', './src/**/*.{ts,tsx}'],",
        "  theme: {",
        "  extend: {",
    ]
    out += block("colors", colours)
    out += block("fontSize", font_size)
    out += block("fontWeight", font_weight)
    out += block("borderRadius", radius)
    out += block("spacing", spacing)
    out += block("boxShadow", shadow)
    out += ["  },", "  },", "  plugins: [],", "} satisfies Config", ""]

    pathlib.Path("frontend/tailwind.config.ts").write_text("\n".join(out), encoding="utf-8")

    print("colours: %d (%d rendered but never declared by GHL)" % (len(colours), unnamed))
    print("fontSize: %d  fontWeight: %d  radius: %d  spacing: %d  shadow: %d"
          % (len(font_size), len(font_weight), len(radius), len(spacing), len(shadow)))
    print("wrote frontend/tailwind.config.ts")


if __name__ == "__main__":
    main()
