"""Turn measured values into a coherent design system, logging every deviation.

Policy (agreed): match GHL exactly on anything structural — layout, spacing, type
scale, primary palette. Normalise *incidental* inconsistencies, and log each one so
none of it is silent and any of it can be overruled.

A value is KEPT if it is used >= KEEP_MIN times, or appears in >= 2 views.
Everything else is mapped to the nearest kept value of the same property.

Plus explicit overrides for defects identified by measurement:
  * rgb(51,51,51)  - Tabulator's own default text colour, leaking into Contacts only.
                     We rebuild that grid on TanStack Table, so it has no reason to exist.
  * 29px radius    - Contacts only, 20 uses, matches nothing else in the system.
"""
import json
import pathlib
import re

KEEP_MIN = 5

OVERRIDES = {
    "color": {
        "rgb(51, 51, 51)": ("rgb(52, 64, 84)",
                            ("Tabulator default leaking into Contacts; grid is "
                             "being rebuilt on TanStack Table")),
    },
    "border-top-left-radius": {
        "29px": ("8px", "Contacts-only one-off, matches nothing else in the system"),
    },
}

# Normalisation may only ever collapse a NEAR-DUPLICATE. It must never recolour
# or resize anything meaningfully.
#
# Learned the hard way: a pure frequency threshold mapped the contact-avatar
# pastels (rgb(249,219,175), rgb(178,204,255), rgb(165,240,252) - each used once
# because every avatar gets its own hue) onto rgb(238,238,238) grey, destroying a
# deliberate palette. Low frequency does NOT mean incidental.
MAX_RGB_DIST = 24      # euclidean in RGB; ~ imperceptible
MAX_PX_DELTA = 1.5     # px

PX = re.compile(r"^-?[\d.]+px$")
RGB = re.compile(r"^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)")


def as_px(v):
    return float(v[:-2]) if PX.match(v) else None


def as_rgb(v):
    """Return (r,g,b) only for fully opaque colours.

    Translucent values are never normalised: alpha carries meaning (overlays,
    scrims, hover washes) that an RGB-only match silently throws away.
    """
    m = RGB.match(v)
    if not m:
        return None
    if m.group(4) is not None and float(m.group(4)) < 1.0:
        return None
    return tuple(int(m.group(i)) for i in (1, 2, 3))


def nearest(val, kept):
    """Nearest kept value, but ONLY if it is within the near-duplicate ceiling."""
    p = as_px(val)
    if p is not None:
        cands = [(abs(as_px(k) - p), k) for k in kept if as_px(k) is not None]
        if cands:
            dist, best = min(cands)
            return best if dist <= MAX_PX_DELTA else None
        return None

    c = as_rgb(val)
    if c is not None:
        cands = []
        for k in kept:
            kc = as_rgb(k)
            if kc:
                cands.append((sum((a - b) ** 2 for a, b in zip(c, kc, strict=True)) ** 0.5, k))
        if cands:
            dist, best = min(cands)
            return best if dist <= MAX_RGB_DIST else None
    return None


def main():
    data = json.loads(pathlib.Path("frontend/tokens.json").read_text(encoding="utf-8"))
    used = data["used"]

    report = ["# Normalisations applied",
              "",
              "Generated by `capture/normalize.py`. Every deviation from measured GHL",
              "values is listed here. Nothing is normalised silently.",
              "",
              "Policy: keep a value if used >= %d times or present in >= 2 views;" % KEEP_MIN,
              "otherwise map to the nearest kept value of the same property.",
              ""]

    system = {}
    total_norm = 0

    for prop, vals in sorted(used.items()):
        counts = {v: sum(c.values()) for v, c in vals.items()}
        views = {v: len(c) for v, c in vals.items()}
        kept = [v for v in vals if counts[v] >= KEEP_MIN or views[v] >= 2]
        dropped = [v for v in vals if v not in kept]

        mapping = {}
        for v in dropped:
            tgt = nearest(v, kept)
            if tgt:
                mapping[v] = (tgt, "used %dx in %d view(s); below threshold"
                              % (counts[v], views[v]))
            else:
                kept.append(v)  # non-numeric, non-colour: keep rather than guess

        for v, (tgt, why) in OVERRIDES.get(prop, {}).items():
            if v in vals:
                mapping[v] = (tgt, why)
                if v in kept:
                    kept.remove(v)

        system[prop] = sorted(kept, key=lambda v: -counts.get(v, 0))

        if mapping:
            total_norm += len(mapping)
            report.append("## `%s` — %d kept, %d normalised" % (prop, len(kept), len(mapping)))
            report.append("")
            report.append("| measured value | uses | mapped to | reason |")
            report.append("|---|---|---|---|")
            for v, (tgt, why) in sorted(mapping.items(), key=lambda kv: -counts.get(kv[0], 0)):
                report.append("| `%s` | %d | `%s` | %s |" % (v, counts.get(v, 0), tgt, why))
            report.append("")

    pathlib.Path("NORMALIZATIONS.md").write_text("\n".join(report), encoding="utf-8")
    pathlib.Path("frontend/design-system.json").write_text(
        json.dumps(system, indent=1), encoding="utf-8")

    print("normalised %d values across %d properties" % (total_norm, len(system)))
    for p in ("font-size", "font-weight", "color", "border-top-left-radius", "gap"):
        if p in system:
            print("  %-24s %d kept" % (p, len(system[p])))
    print("\nwrote NORMALIZATIONS.md and frontend/design-system.json")


if __name__ == "__main__":
    main()
