"""Derive the design system from captures. Nothing here is hand-typed.

Emits:
  design-tokens.md          human-readable, every distinct value with usage counts
  frontend/tokens.json      machine-readable, consumed by tailwind.config.ts

Two sources, kept separate on purpose:
  * DECLARED  - CSS custom properties on :root (the palette GHL ships)
  * USED      - values actually present in computed styles of visible elements
                (the palette GHL actually renders)
They are not the same set, and only the second one is evidence.

Full value sets are emitted, never a top-N: truncating the tail makes rare-but-real
values look like they exist only in our clone when we later diff.
"""
import collections
import json
import pathlib

CAPTURES = pathlib.Path("captures")

# Properties whose value vocabulary defines the design system.
TRACKED = [
    "font-family", "font-size", "font-weight", "line-height", "letter-spacing",
    "color", "background-color",
    "border-top-left-radius", "box-shadow",
    "border-top-width", "border-top-color",
    "padding-top", "padding-right", "padding-bottom", "padding-left",
    "gap", "row-gap", "column-gap",
]

NOISE = {"none", "normal", "auto", "0px", "rgba(0, 0, 0, 0)", "0", ""}


def latest_capture(view):
    d = CAPTURES / view
    if not d.exists():
        return None
    files = sorted(d.glob("*__1440x900__top__*.json"))
    return files[-1] if files else None


def load_all():
    caps = {}
    for view in ("contacts", "conversations", "opportunities", "calendars"):
        f = latest_capture(view)
        if f:
            caps[view] = json.loads(f.read_text(encoding="utf-8"))
    return caps


def main():
    caps = load_all()
    if not caps:
        print("no captures found")
        return

    declared = {}
    for _view, d in caps.items():
        declared.update(d.get("theme", {}))

    # USED: value -> {prop: {view: count}}
    used = collections.defaultdict(lambda: collections.defaultdict(collections.Counter))
    for view, d in caps.items():
        for el in d["elements"]:
            st = el.get("style", {})
            for p in TRACKED:
                v = (st.get(p) or "").strip()
                if v and v not in NOISE:
                    used[p][v][view] += 1

    # Map declared colour tokens back to the values that use them.
    by_value = {}
    for name, val in declared.items():
        by_value.setdefault(val.strip().lower(), []).append(name)

    out_md = ["# Design tokens — measured, not authored",
              "",
              "Generated by `capture/tokens.py` from `captures/`. Do not hand-edit.",
              "",
              "Views measured: " + ", ".join(sorted(caps)),
              "",
              "## Declared CSS custom properties (%d)" % len(declared),
              ""]

    fams = collections.defaultdict(dict)
    for k, v in sorted(declared.items()):
        fams[k.lstrip("-").split("-")[0]][k] = v
    for fam in sorted(fams):
        out_md.append("### `%s` (%d)" % (fam, len(fams[fam])))
        out_md.append("")
        out_md.append("| token | value |")
        out_md.append("|---|---|")
        for k, v in sorted(fams[fam].items()):
            out_md.append("| `%s` | `%s` |" % (k, v))
        out_md.append("")

    out_md += ["## Values actually rendered", ""]
    for p in TRACKED:
        vals = used.get(p)
        if not vals:
            continue
        total = sum(sum(c.values()) for c in vals.values())
        out_md.append("### `%s` — %d distinct values, %d uses"
                      % (p, len(vals), total))
        out_md.append("")
        out_md.append("| value | uses | views | matching token |")
        out_md.append("|---|---|---|---|")
        ranked = sorted(vals.items(), key=lambda kv: -sum(kv[1].values()))
        for val, per_view in ranked:
            tok = by_value.get(val.strip().lower(), [])
            out_md.append("| `%s` | %d | %s | %s |" % (
                val, sum(per_view.values()),
                ", ".join("%s:%d" % (v, n) for v, n in sorted(per_view.items())),
                ", ".join("`%s`" % t for t in tok) if tok else "—"))
        out_md.append("")

    pathlib.Path("design-tokens.md").write_text("\n".join(out_md), encoding="utf-8")

    machine = {
        "declared": declared,
        "used": {p: {v: dict(c) for v, c in vals.items()} for p, vals in used.items()},
        "sourceViews": sorted(caps),
    }
    pathlib.Path("frontend").mkdir(exist_ok=True)
    pathlib.Path("frontend/tokens.json").write_text(
        json.dumps(machine, indent=1), encoding="utf-8")

    print("declared tokens: %d" % len(declared))
    for p in TRACKED:
        if p in used:
            print("  %-24s %3d distinct values" % (p, len(used[p])))
    print("\nwrote design-tokens.md and frontend/tokens.json")


if __name__ == "__main__":
    main()
