"""dispatch_chat_files + dispatch_chat_messages.downloads — spreadsheets uploaded into the
Dispatch chat, compared with Zuper (2026-10-01)

Revision ID: 0dd68d48a507
Revises: 6842fc69cae8
Create Date: 2026-10-01

One NEW table and one NULLABLE column. No DROP, no UPDATE.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0dd68d48a507'
down_revision: str | Sequence[str] | None = '6842fc69cae8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_chat_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sheets', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_chat_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_chat_files_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_chat_files_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_chat_files_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('dispatch_chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downloads', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_chat_messages', schema=None) as batch_op:
        batch_op.drop_column('downloads')

    with op.batch_alter_table('dispatch_chat_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_chat_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_chat_files_message_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_chat_files_chat_id'))

    op.drop_table('dispatch_chat_files')
    # ### end Alembic commands ###
