"""dispatch_jobs, dispatch_calls, dispatch_items, dispatch_events, dispatch_state — the
Dispatch page (2026-09-30)

Revision ID: 116a28895c48
Revises: d7f2b9e4a615
Create Date: 2026-09-30

Five NEW tables. No DROP, no UPDATE, no backfill: nothing that exists changes. Every row is
rebuilt from Zuper by the next read, except an item's Done / Wrong (staff's answer).
DECISIONS.md, the 2026-09-30 Dispatch amendment.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '116a28895c48'
down_revision: str | Sequence[str] | None = 'd7f2b9e4a615'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_uid', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('staff_name', sa.String(length=120), nullable=True),
    sa.Column('job_uids', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_calls_call_uid'), ['call_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_dispatch_calls_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_calls_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('dispatch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('job_uid', sa.String(length=64), nullable=True),
    sa.Column('rang', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_events_key'), ['key'], unique=True)

    op.create_table('dispatch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('queue', sa.String(length=30), nullable=False),
    sa.Column('job_uid', sa.String(length=64), nullable=True),
    sa.Column('job_number', sa.String(length=40), nullable=True),
    sa.Column('board', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('todo', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('urgent', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('close_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_items_job_uid'), ['job_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_items_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_dispatch_items_queue'), ['queue'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_items_state'), ['state'], unique=False)

    op.create_table('dispatch_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_uid', sa.String(length=64), nullable=False),
    sa.Column('job_number', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('board', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('status_type', sa.String(length=40), nullable=True),
    sa.Column('status_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_by', sa.String(length=120), nullable=True),
    sa.Column('customer_uid', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('phones', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('technician', sa.String(length=120), nullable=True),
    sa.Column('zuper_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zuper_updated_at', sa.String(length=40), nullable=True),
    sa.Column('is_open', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('notes_read_for', sa.String(length=40), nullable=True),
    sa.Column('notes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_note_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo_day', sa.String(length=10), nullable=True),
    sa.Column('photos_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_photo_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_photo_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_photo_by', sa.String(length=120), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_jobs_board'), ['board'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_jobs_job_uid'), ['job_uid'], unique=True)

    op.create_table('dispatch_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeded', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calls_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_counts', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatch_state')
    with op.batch_alter_table('dispatch_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_jobs_job_uid'))
        batch_op.drop_index(batch_op.f('ix_dispatch_jobs_board'))

    op.drop_table('dispatch_jobs')
    with op.batch_alter_table('dispatch_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_items_state'))
        batch_op.drop_index(batch_op.f('ix_dispatch_items_queue'))
        batch_op.drop_index(batch_op.f('ix_dispatch_items_key'))
        batch_op.drop_index(batch_op.f('ix_dispatch_items_job_uid'))

    op.drop_table('dispatch_items')
    with op.batch_alter_table('dispatch_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_events_key'))

    op.drop_table('dispatch_events')
    with op.batch_alter_table('dispatch_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_calls_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_dispatch_calls_number'))
        batch_op.drop_index(batch_op.f('ix_dispatch_calls_call_uid'))

    op.drop_table('dispatch_calls')
    # ### end Alembic commands ###
