"""ai_call on both event tables: what an AI agent did on a call

Phase 1 of the 2026-09-22 voice-agent amendment. owen-main answers a call with an agent;
the CRM has to be able to show that it happened, what the agent recorded, and which
campaign the number belongs to.

NULLABLE with no server_default on purpose. Every row that predates this column was
written by a person, a feed or an automation, and "no agent touched this" is exactly what
NULL says; a default of {} would claim an empty agent record for a decade of history.

Both tables, because a voice agent mostly answers STRANGERS — a first-time caller has no
contact, so the events this column exists for land on a number-only thread.


Revision ID: 50c12ee623e2
Revises: f5c1e9a3d742
Create Date: 2026-09-22 17:34:10.189375
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50c12ee623e2'
down_revision: str | Sequence[str] | None = 'f5c1e9a3d742'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_call', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))

    with op.batch_alter_table('number_thread_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_call', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('number_thread_events', schema=None) as batch_op:
        batch_op.drop_column('ai_call')

    with op.batch_alter_table('conversation_events', schema=None) as batch_op:
        batch_op.drop_column('ai_call')

    # ### end Alembic commands ###
