"""dispatch_jobs.visit_photo_at / visit_photo_count / visit_photo_by — a visit's pictures
kept past midnight (the Dispatch page, review fix 2026-10-01)

Revision ID: 5c2aeb6381fa
Revises: f4d9e84f772d
Create Date: 2026-10-01

Three NULLABLE / defaulted columns on dispatch_jobs. No DROP, no UPDATE: "the visit is done,
call the customer" no longer disappears at midnight. DECISIONS.md, the Dispatch amendment.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5c2aeb6381fa'
down_revision: str | Sequence[str] | None = 'f4d9e84f772d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_photo_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('visit_photo_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('visit_photo_by', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_jobs', schema=None) as batch_op:
        batch_op.drop_column('visit_photo_by')
        batch_op.drop_column('visit_photo_count')
        batch_op.drop_column('visit_photo_at')

    # ### end Alembic commands ###
