"""dispatch_chats, dispatch_chat_messages — the Dispatch assistant's conversations, saved
(2026-10-01)

Revision ID: 6842fc69cae8
Revises: 5c2aeb6381fa
Create Date: 2026-10-01

Two NEW tables. No DROP, no UPDATE: every chat, answer and tool step is kept for review.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '6842fc69cae8'
down_revision: str | Sequence[str] | None = '5c2aeb6381fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('suggestion_ids', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_chat_messages_chat_id'), ['chat_id'], unique=False)

    op.create_table('dispatch_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), server_default='New chat', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_chats_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_chats_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_chats_user_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_chats_updated_at'))

    op.drop_table('dispatch_chats')
    with op.batch_alter_table('dispatch_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_chat_messages_chat_id'))

    op.drop_table('dispatch_chat_messages')
    # ### end Alembic commands ###
