"""dispatch_settings, dispatch_suggestions, dispatch_ai_runs + four nullable columns —
the Dispatch page, phase 2 (2026-09-30)

Revision ID: 6988b57e349f
Revises: 116a28895c48
Create Date: 2026-09-30

Three NEW tables and four NULLABLE columns on the phase-1 tables. No DROP, no UPDATE, no
backfill. DECISIONS.md, the 2026-09-30 Dispatch amendment (phase 2).
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '6988b57e349f'
down_revision: str | Sequence[str] | None = '116a28895c48'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ok', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_ai_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_ai_runs_created_at'), ['created_at'], unique=False)

    op.create_table('dispatch_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=120), server_default='gpt-6-luna', nullable=False),
    sa.Column('daily_cap', sa.Integer(), server_default='300', nullable=False),
    sa.Column('technicians', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatch_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('job_uid', sa.String(length=64), nullable=False),
    sa.Column('job_number', sa.String(length=40), nullable=True),
    sa.Column('board', sa.String(length=120), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('field', sa.String(length=200), nullable=False),
    sa.Column('current', sa.Text(), nullable=True),
    sa.Column('proposed', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='explain', nullable=False),
    sa.Column('state', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_suggestions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_suggestions_job_uid'), ['job_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_suggestions_state'), ['state'], unique=False)

    with op.batch_alter_table('dispatch_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True))
        batch_op.add_column(sa.Column('ai_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('ai_error', sa.Text(), nullable=True))

    with op.batch_alter_table('dispatch_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fields', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_jobs', schema=None) as batch_op:
        batch_op.drop_column('fields')

    with op.batch_alter_table('dispatch_items', schema=None) as batch_op:
        batch_op.drop_column('ai_error')
        batch_op.drop_column('ai_at')
        batch_op.drop_column('ai')

    with op.batch_alter_table('dispatch_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_suggestions_state'))
        batch_op.drop_index(batch_op.f('ix_dispatch_suggestions_job_uid'))
        batch_op.drop_index(batch_op.f('ix_dispatch_suggestions_item_id'))

    op.drop_table('dispatch_suggestions')
    op.drop_table('dispatch_settings')
    with op.batch_alter_table('dispatch_ai_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_ai_runs_created_at'))

    op.drop_table('dispatch_ai_runs')
    # ### end Alembic commands ###
