"""saved views for the opportunities board

A named filter set for the Opportunities board — GHL calls these smart lists.
Holds only the filters the board actually has: a pipeline (nullable, meaning
"whichever one is open"), the status filter and the search term.

Generated against a throwaway SQLite database, not `dtr_ghl_clone`: this adds a
table and touches no existing row, but the rule in CLAUDE.md is that migrations
are written away from the working database and applied deliberately.

Revision ID: 79c22cf0590c
Revises: cfbdcb5bf88c
Create Date: 2026-09-10 19:32:22.939013

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '79c22cf0590c'
down_revision: str | Sequence[str] | None = 'cfbdcb5bf88c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('q', sa.String(length=200), server_default='', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_views')
    # ### end Alembic commands ###
