"""delivery lifecycle for real sends

The Conversations composer can now hand a message to owen-main for delivery over
the real BulkVS DID, so `delivery_status` has to carry a lifecycle rather than the
two answers LoggingTransport needed:

  * two new `deliverystatus` values, QUEUED and REFUSED;
  * `conversation_events.delivery_detail`, the sentence explaining a refusal or a
    carrier failure;
  * an index on `conversation_events.provider_ref`, which is how a delivery receipt
    finds the row it is about.

Additive. It creates no table, drops nothing, and rewrites no existing row: every
row keeps the `delivery_status` it has, and `delivery_detail` arrives NULL, which is
what "nothing to explain" already means. Production holds real records (CLAUDE.md)
and this migration is safe against them.

`ALTER TYPE ... ADD VALUE` is why the enum half is written by hand rather than
autogenerated — Alembic does not emit it, and `--autogenerate` sees no change at all
because SQLAlchemy's `Enum` reflects as the same named type whatever its members.
It runs inside the migration transaction, which PostgreSQL has allowed since 12
provided the new value is not USED in that same transaction. It is not: nothing here
writes a row. The host runs PostgreSQL 18 (DECISIONS.md).

`IF NOT EXISTS` makes the enum half idempotent, so a re-run after a partial failure
does not abort on "value already exists".

Generated against a throwaway SQLite database, per CLAUDE.md — SQLite has no enum
type, storing these as VARCHAR with a CHECK-free column, so the ALTER TYPE steps are
skipped there and the tests exercise the new values without a migration at all.

Revision ID: a1f4c7d92b30
Revises: 79c22cf0590c
Create Date: 2026-09-11 10:14:03.882190

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1f4c7d92b30'
down_revision: str | Sequence[str] | None = '79c22cf0590c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NEW_STATUSES = ("QUEUED", "REFUSED")


def upgrade() -> None:
    """Upgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        for value in NEW_STATUSES:
            op.execute("ALTER TYPE deliverystatus ADD VALUE IF NOT EXISTS '%s'" % value)

    op.add_column(
        'conversation_events',
        sa.Column('delivery_detail', sa.Text(), nullable=True),
    )
    op.create_index(
        'ix_conversation_events_provider_ref',
        'conversation_events', ['provider_ref'],
    )


def downgrade() -> None:
    """Downgrade schema.

    The column and the index come back out. **The enum values do not**, and cannot:
    PostgreSQL has no `ALTER TYPE ... DROP VALUE`, and the only way to remove one is
    to build a replacement type and rewrite every column using it. Doing that on the
    way down would be a far more dangerous operation than the upgrade it reverses.

    Leaving them is harmless — an unused enum value costs nothing — but it does mean
    this downgrade is not a perfect inverse, so it is written down rather than
    discovered. A row already written QUEUED or REFUSED keeps that value and would
    read back fine; it is the application, not the database, that would no longer
    know the word.
    """
    op.drop_index('ix_conversation_events_provider_ref',
                  table_name='conversation_events')
    op.drop_column('conversation_events', 'delivery_detail')
