"""dispatch_write_log + six switches on dispatch_settings + three nullable columns on
dispatch_suggestions — the Dispatch page, phase 3 (2026-10-01)

Revision ID: f4d9e84f772d
Revises: 6988b57e349f
Create Date: 2026-10-01

One NEW table, six NOT NULL booleans that default to FALSE (every "let the agent do it"
switch starts off, existing row included) and three NULLABLE columns. No DROP, no UPDATE, no
backfill. DECISIONS.md, the 2026-09-30 Dispatch amendment (phase 3).
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f4d9e84f772d'
down_revision: str | Sequence[str] | None = '6988b57e349f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_write_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('job_uid', sa.String(length=64), nullable=True),
    sa.Column('job_number', sa.String(length=40), nullable=True),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('sentence', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_write_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_write_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_write_log_job_uid'), ['job_uid'], unique=False)

    with op.batch_alter_table('dispatch_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writes_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('write_fields', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('write_address', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('write_note', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('write_booking', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('write_stage', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('dispatch_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('applied_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('apply_result', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_suggestions', schema=None) as batch_op:
        batch_op.drop_column('apply_result')
        batch_op.drop_column('applied_by_id')
        batch_op.drop_column('applied_at')

    with op.batch_alter_table('dispatch_settings', schema=None) as batch_op:
        batch_op.drop_column('write_stage')
        batch_op.drop_column('write_booking')
        batch_op.drop_column('write_note')
        batch_op.drop_column('write_address')
        batch_op.drop_column('write_fields')
        batch_op.drop_column('writes_enabled')

    with op.batch_alter_table('dispatch_write_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_write_log_job_uid'))
        batch_op.drop_index(batch_op.f('ix_dispatch_write_log_at'))

    op.drop_table('dispatch_write_log')
    # ### end Alembic commands ###
